
###

GET http://localhost:3333/albuns

###

POST http://localhost:3333/albuns
Content-Type: application/json

{
    "nome": "a",
    "banda": "",
    "faixas": ""
}

###

PUT http://localhost:3333/albuns/
Content-Type: application/json

{
    "nome": "",
    "banda": "",
    "faixas": ""
}

###

DELETE http://localhost:3333/albuns/
